### ISSUE TITLE
Using Self-supervised Learning for Precise Pick-and-place without Object Model with a KUKA iiwa

### ISSUE THREAD

**Issue by Marcelbgit** [pantor/learning-pick-and-place#5]
Hello Pantor,

thanks for sharing your very exciting work and code! Is it possible to adapt your code to a KUKA iiwa? What steps would be necessary here? Replacing the launch and include files would be my guess. Are there also other interfaces that I need to adapt for this. I would be glad about the help and answer. I would like to test and develop your code for other applications.

Best regards,
Marcel

**Comment by pantor** [comment]
Hi Marcel,

it is definitely possible to adapt this project for the Kuka iiwa! Please keep in mind that this repository is not meant to be plug-and-play, so it will be a bit of work to integrate all your hardware (robot, camera, gripper) and setting up the software. You can also have a look at [Griffig](https://github.com/pantor/griffig), which currently only does grasp calculation, but might be a useful to understand the abstraction between manipulation planning and robot control.

Anyway, you are right that you would primarily need to adapt the [Robot class](https://github.com/pantor/learning-pick-and-place/blob/0fc227e2118f59902572d354668c00a4482fd21a/include/frankr/robot.hpp#L36), the launch files, and a few things in  [config.py](https://github.com/pantor/learning-pick-and-place/blob/master/scripts/config.py). If there are any more specific questions, feel free to ask.
